# Generated by Django 4.2 on 2023-04-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='author',
            new_name='user',
        ),
    ]
